### ISSUE TITLE
Example of CSS that breaks updates

### ISSUE THREAD

**Issue by sergeche** [livestyle/chrome#14]
Editing property at line 90 generates too much patches that mistakenly remove important rules

``` css
.reel {
    position: relative;
}

.reel__screen {
    position: relative;
    width: 100vw;
    height: 100vh;
    background: 50% 50% no-repeat;
}

.reel__screen-content {
    position: relative;
    padding: 20px;
    margin: 0 auto;
    top: 200px;
    color: #fff;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

.reel__screen-content_main {
    max-width: 600px;
    width: 70%;
}

.reel__screen-content_aside {
    max-width: 400px;
    width: 30%;
}

.reel_aside {
    z-index: 2;
    top: 0;
    right: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
    position: fixed;
    will-change: transform, clip;
}

.reel_aside[data-lineage="ertheia"] {
    clip: rect(auto, auto, auto, 70vw);
}

.reel_aside[data-lineage="classic"] {
    clip: rect(auto, 30vw, auto, auto);
}

.reel__separator {
    content: '';
    display: block;
    width: 1px;
    background: #fff;
    opacity: 0.4;
    height: 100%;
    z-index: 3;
    position: fixed;
}

.reel__screen_classes {
    background-image: url(./img/bg/classes.jpg);
}

.reel__screen_leveling {
    background-image: url(./img/bg/leveling.jpg);
}

.reel__screen_economics {
    background-image: url(./img/bg/economics.jpg);
}

.reel__screen_clans {
    background-image: url(./img/bg/clans.jpg);
}


.reel_main .reel__screen-content_aside, .reel_aside .reel__screen-content_main {
    display: none;
}


.reel[data-lineage="classic"] .reel__screen-content_main {
    left: -15%;
}

.reel[data-lineage="classic"] .reel__screen-content_aside {
    left: -35%;
}


.reel[data-lineage="ertheia"] .reel__screen-content_main {
    left: -15%;
}


.reel[data-lineage="ertheia"] .reel__screen-content_aside {
    left: 35%;
}


.reel__separator[data-lineage="classic"] {
    left: 70%;
}


.reel__separator[data-lineage="ertheia"] {
    left: 30%;
}


.reel__screen_main {
    background-image: url(./img/bg/main.jpg);
}
```
