### ISSUE TITLE
Failing example

### ISSUE THREAD

**Issue by sergeche** [livestyle/chrome#4]
``` css
.page-header__play {
    position: absolute;
    background: url(../../img/yt-play-button.png);
    width: 85px;
    height: 60px;
    top: 30%;
    left: 50%;
    margin-top: -30px;
    margin-left: -42px;
    cursor: pointer;
    -webkit-background-size: cover;
    background-size: cover;
}
```

Removing `cursor: pointer;` breaks `background-size` in browser
